import { Suspense } from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import Loading from "./loading";
import { ThemeProvider } from "@/context/themeContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={roboto.className}>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </body>
      </html>
    </ThemeProvider>
  );
}
